print("dungeon quest of Black fortress")
print("-------------------------------")
print("Cultist [4]")
print()
print("[1] punch")
print("[2] amulet of Baal")
print("[3] attack")
print()
print("-------------------------------")
print("10/10 HP     2 command       3 munition      2 combat")